// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`extensions.itx (provider=cockroachdb) extended client in itx can rollback via custom call 1`] = `

Invalid \`prisma.user.create()\` invocation:


Unique constraint failed on the fields: (\`email\`)
`;

exports[`extensions.itx (provider=cockroachdb) extended client in itx can rollback via normal call 1`] = `

Invalid \`tx.user.create()\` invocation in
/client/tests/functional/extensions/itx.ts:0:0

  XX   },
  XX })
  XX 
→ XX await tx.user.create(
Unique constraint failed on the fields: (\`email\`)
`;

exports[`extensions.itx (provider=mongodb) extended client in itx can rollback via custom call 1`] = `

Invalid \`prisma.user.create()\` invocation:


Unique constraint failed on the constraint: \`User_email_key\`
`;

exports[`extensions.itx (provider=mongodb) extended client in itx can rollback via normal call 1`] = `

Invalid \`tx.user.create()\` invocation in
/client/tests/functional/extensions/itx.ts:0:0

  XX   },
  XX })
  XX 
→ XX await tx.user.create(
Unique constraint failed on the constraint: \`User_email_key\`
`;

exports[`extensions.itx (provider=mysql) extended client in itx can rollback via custom call 1`] = `

Invalid \`prisma.user.create()\` invocation:


Unique constraint failed on the constraint: \`User_email_key\`
`;

exports[`extensions.itx (provider=mysql) extended client in itx can rollback via normal call 1`] = `

Invalid \`tx.user.create()\` invocation in
/client/tests/functional/extensions/itx.ts:0:0

  XX   },
  XX })
  XX 
→ XX await tx.user.create(
Unique constraint failed on the constraint: \`User_email_key\`
`;

exports[`extensions.itx (provider=mysql,providerFlavor=js_planetscale) extended client in itx can rollback via custom call 1`] = `target: tests.0.primary: vttablet: rpc error: code = AlreadyExists desc = Duplicate entry 'jane@smith.com' for key 'User.User_email_key' (errno 1062) (sqlstate 23000) (CallerID: userData1): Sql: "insert into \`User\`(id, email, firstName, lastName) values (:vtg1 /* VARCHAR */, :vtg2 /* VARCHAR */, :vtg3 /* VARCHAR */, :vtg4 /* VARCHAR */)", BindVars: {vtg1: "type:VARCHAR value:\\"clm0kaeyb000g4pzd4glpfi7z\\""vtg2: "type:VARCHAR value:\\"jane@smith.com\\""vtg3: "type:VARCHAR value:\\"Jane\\""vtg4: "type:VARCHAR value:\\"Smith\\""} (errno 1062) (sqlstate 23000) during query: INSERT INTO \`tests\`.\`User\` (\`id\`,\`email\`,\`firstName\`,\`lastName\`) VALUES ('clm0kaeyb000g4pzd4glpfi7z','jane@smith.com','Jane','Smith')`;

exports[`extensions.itx (provider=mysql,providerFlavor=js_planetscale) extended client in itx can rollback via normal call 1`] = `target: tests.0.primary: vttablet: rpc error: code = AlreadyExists desc = Duplicate entry 'jane@smith.com' for key 'User.User_email_key' (errno 1062) (sqlstate 23000) (CallerID: userData1): Sql: "insert into \`User\`(id, email, firstName, lastName) values (:vtg1 /* VARCHAR */, :vtg2 /* VARCHAR */, :vtg3 /* VARCHAR */, :vtg4 /* VARCHAR */)", BindVars: {vtg1: "type:VARCHAR value:\\"clm0kaern00074pzdelfqgvbn\\""vtg2: "type:VARCHAR value:\\"jane@smith.com\\""vtg3: "type:VARCHAR value:\\"Jane\\""vtg4: "type:VARCHAR value:\\"Smith\\""} (errno 1062) (sqlstate 23000) during query: INSERT INTO \`tests\`.\`User\` (\`id\`,\`email\`,\`firstName\`,\`lastName\`) VALUES ('clm0kaern00074pzdelfqgvbn','jane@smith.com','Jane','Smith')`;

exports[`extensions.itx (provider=mysql,providerFlavor=vitess_8) extended client in itx can rollback via custom call 1`] = `

Invalid \`prisma.user.create()\` invocation:


Unique constraint failed on the (not available)
`;

exports[`extensions.itx (provider=mysql,providerFlavor=vitess_8) extended client in itx can rollback via normal call 1`] = `

Invalid \`tx.user.create()\` invocation in
/client/tests/functional/extensions/itx.ts:0:0

  XX   },
  XX })
  XX 
→ XX await tx.user.create(
Unique constraint failed on the (not available)
`;

exports[`extensions.itx (provider=postgresql) extended client in itx can rollback via custom call 1`] = `

Invalid \`prisma.user.create()\` invocation:


Unique constraint failed on the fields: (\`email\`)
`;

exports[`extensions.itx (provider=postgresql) extended client in itx can rollback via normal call 1`] = `

Invalid \`tx.user.create()\` invocation in
/client/tests/functional/extensions/itx.ts:0:0

  XX   },
  XX })
  XX 
→ XX await tx.user.create(
Unique constraint failed on the fields: (\`email\`)
`;

exports[`extensions.itx (provider=sqlite) extended client in itx can rollback via custom call 1`] = `

Invalid \`prisma.user.create()\` invocation:


Unique constraint failed on the fields: (\`email\`)
`;

exports[`extensions.itx (provider=sqlite) extended client in itx can rollback via normal call 1`] = `

Invalid \`tx.user.create()\` invocation in
/client/tests/functional/extensions/itx.ts:0:0

  XX   },
  XX })
  XX 
→ XX await tx.user.create(
Unique constraint failed on the fields: (\`email\`)
`;

exports[`extensions.itx (provider=sqlserver) extended client in itx can rollback via custom call 1`] = `

Invalid \`prisma.user.create()\` invocation:


Unique constraint failed on the constraint: \`dbo.User\`
`;

exports[`extensions.itx (provider=sqlserver) extended client in itx can rollback via normal call 1`] = `

Invalid \`tx.user.create()\` invocation in
/client/tests/functional/extensions/itx.ts:0:0

  XX   },
  XX })
  XX 
→ XX await tx.user.create(
Unique constraint failed on the constraint: \`dbo.User\`
`;
